<?php
$data = array (
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '手机分类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '7',
    'sort_order' => '1',
    'has_children' => '25',
    'goods_num' => 0,
    'level' => 0,
    'id' => '43',
    'name' => '手机分类',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '魅族',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '14',
    'level' => 1,
    'id' => '36',
    'name' => '魅族',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '微软',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '56',
    'name' => '微软',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '语信',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '53',
    'name' => '语信',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '海信',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '40',
    'name' => '海信',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => 'LG',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '49',
    'name' => 'LG',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '华硕',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '38',
    'name' => '华硕',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => 'oppo',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 1,
    'id' => '32',
    'name' => 'oppo',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '一加',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '57',
    'name' => '一加',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '乐视',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '37',
    'name' => '乐视',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '美图',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '54',
    'name' => '美图',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '诺基亚',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '44',
    'name' => '诺基亚',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => 'TCL',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '50',
    'name' => 'TCL',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '小米',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '25',
    'level' => 1,
    'id' => '34',
    'name' => '小米',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '联想',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => '联想',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '金立',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '16',
    'level' => 1,
    'id' => '41',
    'name' => '金立',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '三星',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '62',
    'level' => 1,
    'id' => '31',
    'name' => '三星',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '酷派',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '58',
    'name' => '酷派',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '华为',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '74',
    'level' => 1,
    'id' => '35',
    'name' => '华为',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '锤子',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '锤子',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '360奇酷',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '39',
    'name' => '360奇酷',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '中兴',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '52',
    'name' => '中兴',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '苹果',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '16',
    'level' => 1,
    'id' => '30',
    'name' => '苹果',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '天语',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => '天语',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => 'HTC',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => 'HTC',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => 'vivo',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 1,
    'id' => '33',
    'name' => 'vivo',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '平板专区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '2',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '60',
    'name' => '平板专区',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '苹果',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 1,
    'id' => '62',
    'name' => '苹果',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '智能腕表',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '59',
    'name' => '智能腕表',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '华为',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '74',
    'name' => '华为',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '三星',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '71',
    'name' => '三星',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '360',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '75',
    'name' => '360',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '72',
    'name' => '其他',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '苹果',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '73',
    'name' => '苹果',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '小天才',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '70',
    'name' => '小天才',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '手机储存卡',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '63',
    'name' => '手机储存卡',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '闪迪',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '81',
    'name' => '闪迪',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '金士顿',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '82',
    'name' => '金士顿',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '东芝',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '83',
    'name' => '东芝',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '万能读卡',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '80',
    'name' => '万能读卡',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '移动电源',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '5',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '64',
    'name' => '移动电源',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '乐友',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '78',
    'name' => '乐友',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '酷派',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '79',
    'name' => '酷派',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '羽博',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '76',
    'name' => '羽博',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '米格',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '77',
    'name' => '米格',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '耳机 音响',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '65',
    'name' => '耳机 音响',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '苹果',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '90',
    'name' => '苹果',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '捷波朗',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '91',
    'name' => '捷波朗',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '小米',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '88',
    'name' => '小米',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '89',
    'name' => '其他',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '数据线 充电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '66',
    'name' => '数据线 充电器',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '保护壳',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '8',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '67',
    'name' => '保护壳',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '定制',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '94',
    'name' => '定制',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '三星',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '92',
    'name' => '三星',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '苹果',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '93',
    'name' => '苹果',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '9',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '69',
    'name' => '其他',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '保护膜',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '87',
    'name' => '保护膜',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '车载配件',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '68',
    'name' => '车载配件',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => 'u盘',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '84',
    'name' => 'u盘',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '电视机顶盒',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '85',
    'name' => '电视机顶盒',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '电池',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '86',
    'name' => '电池',
  ),
);
?>